import './styles.scss';
type Incident={id:string;title:string;service:string;severity:string;status:string;started_at:string;customer_impact:string};
const apiBase='http://localhost:8080/api';
const fallbackIncidents:Incident[]=[{id:'INC-2026-0042',title:'Checkout API returning 500 errors',service:'checkout-api',severity:'SEV-1',status:'Investigating',started_at:'2026-03-18T14:32:00Z',customer_impact:'Payment attempts failing for EU customers'},{id:'INC-2026-0043',title:'Search API latency spike',service:'search-api',severity:'SEV-2',status:'Mitigated',started_at:'2026-03-19T10:12:00Z',customer_impact:'Marketplace search results loading slowly'},{id:'INC-2026-0044',title:'Email queue backlog',service:'email-worker',severity:'SEV-2',status:'Monitoring',started_at:'2026-03-20T08:05:00Z',customer_impact:'Delayed transactional emails'}];
const root=document.querySelector('app-root')!;
async function fetchIncidents():Promise<Incident[]>{try{const r=await fetch(`${apiBase}/incidents`);return (await r.json()).data}catch{return fallbackIncidents}}
async function analyze(id:string){const panel=document.querySelector('#analysis-panel')!;panel.innerHTML='<div class="loading">AI Copilot is correlating logs, deployments, metrics and runbooks...</div>';try{const r=await fetch(`${apiBase}/incidents/${id}/analyze`,{method:'POST'});const{data}=await r.json();const a=data.analysis;panel.innerHTML=`<div class="analysis-card"><div class="eyebrow">AI Root Cause Hypothesis</div><h2>${a.likely_root_cause}</h2><p>${a.summary}</p><div class="confidence"><span style="width:${Math.round(a.confidence*100)}%"></span></div><strong>${Math.round(a.confidence*100)}% confidence</strong></div><div class="grid two"><section class="panel"><h3>Evidence</h3><ul>${a.evidence.map((e:string)=>`<li>${e}</li>`).join('')}</ul></section><section class="panel"><h3>Recommended Actions</h3><ul>${a.recommended_actions.map((e:string)=>`<li>${e}</li>`).join('')}</ul></section></div><section class="panel"><h3>Matched Runbook</h3><p>${data.runbook?.title??'No runbook matched'}</p></section>`}catch{panel.innerHTML='<div class="analysis-card"><h2>Fallback demo mode</h2><p>Start the PHP API to generate live analysis.</p></div>'}}
function severityClass(s:string):string{return s==='SEV-1'?'critical':'warning'}
async function render(){const incidents=await fetchIncidents();root.innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><span>AI</span><strong>Incident Copilot</strong></div><nav><a class="active">Dashboard</a><a>Incidents</a><a>Logs</a><a>Runbooks</a><a>Reports</a></nav></aside><main><header class="hero"><div><div class="eyebrow">Production Engineering Assistant</div><h1>Debug incidents faster with AI-powered signal correlation.</h1><p>Logs, deployments, metrics and runbooks are analyzed together to generate root-cause hypotheses and action plans.</p></div><button id="primary-analyze">Analyze SEV-1 Incident</button></header><section class="stats"><article><strong>${incidents.length}</strong><span>Active incidents</span></article><article><strong>87%</strong><span>Top confidence</span></article><article><strong>4</strong><span>Runbooks matched</span></article><article><strong>12m</strong><span>Estimated time saved</span></article></section><section class="grid two"><div class="panel"><h3>Incident Queue</h3><div class="incident-list">${incidents.map(i=>`<button class="incident" data-id="${i.id}"><span class="badge ${severityClass(i.severity)}">${i.severity}</span><strong>${i.title}</strong><small>${i.service} · ${i.status}</small><p>${i.customer_impact}</p></button>`).join('')}</div></div><div id="analysis-panel"><div class="analysis-card"><div class="eyebrow">Ready</div><h2>Select an incident to start AI analysis</h2><p>The copilot will correlate logs, recent deployments, metrics and runbooks.</p></div></div></section></main></div>`;document.querySelector('#primary-analyze')?.addEventListener('click',()=>analyze(incidents[0].id));document.querySelectorAll('.incident').forEach(el=>el.addEventListener('click',()=>analyze((el as HTMLElement).dataset.id!)))}
render();
